services:
  _defaults:
    autowire: true
    autoconfigure: true

  # SERVICES
  itech_world.sulu_article_twig_extension_filter.article_service:
    class: ItechWorld\SuluArticleTwigExtensionFilterBundle\Service\ArticleService
    public: true
    arguments:
      - '@sulu_article.article_repository'
      - '@sulu_content.content_manager'
      - '@doctrine.orm.entity_manager'
      - '@request_stack'
      - '@sulu_core.webspace.webspace_manager'

  # TWIG EXTENSIONS
  itech_world.sulu_article_twig_extension_filter.article_extension:
    class: ItechWorld\SuluArticleTwigExtensionFilterBundle\Twig\ArticleViewDocumentTwigExtension
    public: true
    arguments:
      - '@itech_world.sulu_article_twig_extension_filter.article_service'
    tags:
      - { name: 'twig.extension' }
